def parts(x):
    if x == 0:
        print('   ',   '------')
        print('   ',   '|    |')
        print('   ',   '|     ')
        print('   ',   '|     ')
        print('   ',   '|     ')
        print('   ',   '|     ')
        print('------------')
    if x == 1:
        print('   ',   '------')
        print('   ',   '|    |')
        print('   ',   '|    o')
        print('   ',   '|     ')
        print('   ',   '|     ')
        print('   ',   '|     ')
        print('------------')
    if x == 2:
        print('   ',   '------')
        print('   ',   '|    |')
        print('   ',   '|    o')
        print('   ',   '|   -|-')
        print('   ',   '|     ')
        print('   ',   '|     ')
        print('------------')
    if x == 3:
        print('   ',   '------')
        print('   ',   '|    |')
        print('   ',   '|    o')
        print('   ',   '|   -|-')
        print('   ',   '|    | ')
        print('   ',   '|     ')
        print('------------')
    if x == 4:
        print('   ',   '------')
        print('   ',   '|    |')
        print('   ',   '|    o')
        print('   ',   '|   -|-')
        print('   ',   '|    | ')
        print('   ',   '|   / \\')
        print('------------')
